import 'package:flutter/material.dart';
import 'package:practice_1/dart_model/custom_data_model.dart';

class ModelClasses extends StatelessWidget {
  List<String> employees = [
    "Soumi",
    "Neel",
    "Pooja",
    "Sourya",
    "Gambu",
    "Shampoo"
  ];

  List<EmployeeDetails> details = [
    EmployeeDetails(id: 1, name: "Soumi", isActive: true),
    EmployeeDetails(id: 2, name: "Golu", isActive: false),
    EmployeeDetails(id: 3, name: "Neel", isActive: true),
    EmployeeDetails(id: 4, name: "Gambu", isActive: false),
    EmployeeDetails(id: 5, name: "Sourya", isActive: true),
    EmployeeDetails(id: 6, name: "Pooja", isActive: true),
    EmployeeDetails(id: 7, name: "Shampoo", isActive: false)
  ];

  List<Autogenerated> employeeList = [
    Autogenerated(name: "Soumi", role: "Android developer", isActive: true),
    Autogenerated(name: "Golu", role: "web developer", isActive: false),
    Autogenerated(name: "Neel", role: "flutter developer", isActive: true),
    Autogenerated(name: "Gambu", role: "angular developer", isActive: false),
    Autogenerated(name: "Sourya", role: "software developer", isActive: true),
    Autogenerated(name: "Shampoo", role: "ios developer", isActive: false),
    Autogenerated(name: "Pooja", role: "react developer", isActive: true),
    Autogenerated(name: "Momo", role: "frontend developer", isActive: false),
    Autogenerated(name: "Guwei", role: "backend developer", isActive: true)
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("Model Class"),
        ),
        body: ListView.builder(
            itemCount: employeeList.length,
            itemBuilder: (context, index) {
              return ListTile(
                // leading: CircleAvatar(
                //   backgroundColor: Colors.blue[100],
                //   child: Text(
                //     employeeList[index].id.toString(),
                //     style: TextStyle(fontWeight: FontWeight.bold),
                //   ),
                // ),
                leading: CircleAvatar(
                  child: Icon(Icons.person),
                ),
                title: Text(employeeList[index].name.toString()),
                subtitle: Text(employeeList[index].role.toString()),
                trailing: IconButton(
                    onPressed: () {},
                    icon: Icon(
                      Icons.star,
                      color: employeeList[index].isActive == true
                          ? const Color.fromARGB(255, 248, 223, 1)
                          : Colors.grey,
                    )),
              );
            }));
  }
}

class EmployeeDetails {
  int id;
  String name;
  bool isActive;

  EmployeeDetails(
      {required this.id, required this.name, required this.isActive});
}
